server:
  port: 9090
#=========================spring=========================
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: iot-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: false
      web-stat-filter:
        enabled: false
    url: jdbc:mysql://localhost:3306/third_app?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12
#=========================eureka=========================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true
#=========================mybatis-plus=========================
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/*.xml